-- 교보문고
CREATE TABLE DEC22_KYOBO (
K_LOCATION VARCHAR2(10 CHAR) PRIMARY KEY,
K_ADDRESS VARCHAR2(20 CHAR) NOT NULL,
K_SIZE NUMBER(4) NOT NULL
);

DROP table DEC22_KYOBO CASCADE CONSTRAINT PURGE;
DROP table DEC22_SELL CASCADE CONSTRAINT PURGE;

-- 책 
CREATE TABLE DEC22_BOOK (
B_NO NUMBER(5) PRIMARY KEY,
B_TITLE VARCHAR2(20 CHAR) NOT NULL,
B_CATEGORY VARCHAR2(10 CHAR) NOT NULL,
B_PRICE NUMBER(6) NOT NULL,
B_DATE DATE NOT NULL
);



-- 판매
CREATE TABLE DEC22_SELL (
S_NO NUMBER(5) PRIMARY KEY,
S_K_LOCATION VARCHAR2(10 CHAR) NOT NULL,
S_B_NO NUMBER(5) NOT NULL,
S_B_STOCK NUMBER(2) NOT NULL,
-- 지점과 판매 사이 외래키 설정
CONSTRAINT KYOBO_C FOREIGN KEY (S_K_LOCATION) REFERENCES DEC22_KYOBO(K_LOCATION) ON DELETE CASCADE,
-- 책과 판매 사이 외래키 설정 
CONSTRAINT BOOK_C FOREIGN KEY (S_B_NO) REFERENCES DEC22_BOOK(B_NO) ON DELETE CASCADE
);


INSERT INTO DEC22_KYOBO VALUES ('강남점', '서초구123', 100);
INSERT INTO DEC22_KYOBO VALUES ('분당점', '분당구456', 100);
INSERT INTO DEC22_KYOBO VALUES ('용인점', '수지구789', 100);
INSERT INTO DEC22_KYOBO VALUES ('수원점', '장안구5678', 100);

CREATE SEQUENCE DEC22_BOOK_SEQ;
INSERT INTO DEC22_BOOK VALUES (DEC22_BOOK_SEQ.NEXTVAL, '이것이 자바다', 'IT', 30000, TO_DATE('20210101', 'YYYYMMDD'));
INSERT INTO DEC22_BOOK VALUES (DEC22_BOOK_SEQ.NEXTVAL, '데이터베이스', 'IT', 35000, TO_DATE('20220101', 'YYYYMMDD'));
INSERT INTO DEC22_BOOK VALUES (DEC22_BOOK_SEQ.NEXTVAL, '요리백과', '생활', 15000, TO_DATE('20201115','YYYYMMDD'));
INSERT INTO DEC22_BOOK VALUES (DEC22_BOOK_SEQ.NEXTVAL, '과학사전', '과학', 48000, TO_DATE('20190808', 'YYYYMMDD'));

CREATE SEQUENCE DEC22_SELL_SEQ;
INSERT INTO DEC22_SELL VALUES(DEC22_SELL_SEQ.NEXTVAL, '강남점', 1, 3);
INSERT INTO DEC22_SELL VALUES(DEC22_SELL_SEQ.NEXTVAL, '강남점', 2, 2);
INSERT INTO DEC22_SELL VALUES(DEC22_SELL_SEQ.NEXTVAL, '강남점', 3, 1);
INSERT INTO DEC22_SELL VALUES(DEC22_SELL_SEQ.NEXTVAL, '강남점', 4, 1);
INSERT INTO DEC22_SELL VALUES(DEC22_SELL_SEQ.NEXTVAL, '분당점', 3, 1);
INSERT INTO DEC22_SELL VALUES(DEC22_SELL_SEQ.NEXTVAL, '용인점', 2, 2);


SELECT * FROM DEC22_KYOBO;
SELECT * FROM DEC22_BOOK;
SELECT * FROM DEC22_SELL;

-- 크기가 5평 이상인 지점
-- 지점별 카테고리별 평균가
-- 평균가가 1000원 미만인건 제외 
---------------------------------------
-- SELL과 BOOK 조인
SELECT S_K_LOCATION, B_CATEGORY, AVG(B_PRICE) FROM DEC22_SELL, DEC22_BOOK WHERE S_B_NO = B_NO AND S_K_LOCATION IN (SELECT K_LOCATION FROM DEC22_KYOBO WHERE K_SIZE >= 5)
GROUP BY S_K_LOCATION, B_CATEGORY HAVING AVG(B_PRICE) >= 1000 ORDER BY S_K_LOCATION, B_CATEGORY;
----------------------------------------
SELECT B_TITLE, B_CATEGORY, B_PRICE, B_DATE 
FROM DEC22_BOOK 
WHERE B_NO IN 
(SELECT S_B_NO 
FROM DEC22_SELL 
WHERE S_K_LOCATION LIKE '%강%');
-----------------------------------------
SELECT B_CATEGORY, AVG(B_PRICE)
FROM DEC22_BOOK 
WHERE B_NO IN 
(SELECT S_B_NO 
FROM DEC22_SELL 
WHERE S_K_LOCATION LIKE '%강%')
GROUP BY B_CATEGORY;




