-- 요식업 프렌차이즈
-- 홍길동, 1999-01-01. 수원, 김밥천국, 강남, 10테이블
-- 		야채김밥, 식사류, 4000원 
-- 		제육덮밥, 식사류, 6000원

-- 김길동, 2000-12-12, 안양, 우동천국, 구로, 8테이블
-- 		기본우동, 식사류, 5000원
-- 		소주, 주류, 5000원 

-- 사장
CREATE TABLE DEC20_CEO(
C_NO NUMBER(3) PRIMARY KEY,
C_NAME VARCHAR2(10 CHAR) NOT NULL,
C_BIRT DATE NOT NULL,
C_HOME VARCHAR2(5 CHAR) NOT NULL
);

CREATE SEQUENCE DEC20_CEO_SEQ;
INSERT INTO DEC20_CEO VALUES (DEC20_CEO_SEQ.NEXTVAL, '홍길동', TO_DATE('19990101', 'YYYYMMDD'), '수원');
INSERT INTO DEC20_CEO VALUES (DEC20_CEO_SEQ.NEXTVAL, '김길동', TO_DATE('20001212', 'YYYYMMDD'), '안양');

-- 식당
CREATE TABLE DEC20_RESTAURANT(
C_NO NUMBER(3) PRIMARY KEY,
R_RES_NAME VARCHAR2(10 CHAR) NOT NULL,
R_LOCATION VARCHAR(5 CHAR) NOT NULL,
R_TABLE NUMBER(3) NOT NULL
);

CREATE SEQUENCE DEC20_RESTAURANT_SEQ;
INSERT INTO DEC20_RESTAURANT VALUES (DEC20_RESTAURANT_SEQ.NEXTVAL, '김밥천국', '강남', 10);
INSERT INTO DEC20_RESTAURANT VALUES (DEC20_RESTAURANT_SEQ.NEXTVAL, '우동천국', '구로', 8);
INSERT INTO DEC20_RESTAURANT VALUES (DEC20_RESTAURANT_SEQ.NEXTVAL, '커피천국', '부산', 15);


-- 메뉴
CREATE TABLE DEC20_MENU(
M_NO NUMBER(3) PRIMARY KEY,
M_NAME VARCHAR2(10 CHAR) NOT NULL,
M_CATEGORY VARCHAR2(5 CHAR) NOT NULL,
M_PRICE NUMBER(5) NOT NULL,
M_RE_NO NUMBER(3) NOT NULL
);

CREATE SEQUENCE DEC20_MENU_SEQ;
INSERT INTO DEC20_MENU VALUES (DEC20_MENU_SEQ.NEXTVAL, '야채김밥', '식사류', 4000, 1);
INSERT INTO DEC20_MENU VALUES (DEC20_MENU_SEQ.NEXTVAL, '제육덮밥', '식사류', 6000, 1);
INSERT INTO DEC20_MENU VALUES (DEC20_MENU_SEQ.NEXTVAL, '기본우동', '식사류', 5000, 2);
INSERT INTO DEC20_MENU VALUES (DEC20_MENU_SEQ.NEXTVAL, '소주', '주류', 5000, 2);
INSERT INTO DEC20_MENU VALUES (DEC20_MENU_SEQ.NEXTVAL, '아메리카노', '음료', 3000, 3);


DROP table DEC20_MENU CASCADE CONSTRAINT PURGE;

-- 운영
CREATE TABLE DEC20_RUN(
R_NO NUMBER(3) PRIMARY KEY,
R_NO_CEO NUMBER(3) NOT NULL,
R_NO_RESTAURANT NUMBER(3) NOT NULL
);

CREATE SEQUENCE DEC20_RUN_SEQ;
INSERT INTO DEC20_RUN VALUES(DEC20_RUN_SEQ.NEXTVAL, 1, 1);
INSERT INTO DEC20_RUN VALUES(DEC20_RUN_SEQ.NEXTVAL, 2, 2);
INSERT INTO DEC20_RUN VALUES(DEC20_RUN_SEQ.NEXTVAL, 1, 3);



SELECT * FROM DEC20_CEO;
SELECT * FROM DEC20_RESTAURANT;
SELECT * FROM DEC20_MENU;
SELECT * FROM DEC20_RUN;

--------------------------------------------------------------------------------------------------

-- 전체 메뉴명, 가격
SELECT M_NAME, M_PRICE FROM DEC20_MENU;

-- 메뉴 평균가
SELECT AVG(M_PRICE) FROM DEC20_MENU;

-- 가장 비싼 메뉴명
SELECT M_NAME FROM DEC20_MENU WHERE M_PRICE = (SELECT MAX(M_PRICE) FROM DEC20_MENU);

-- 강남에 있는 매장명, 테이블 수
SELECT R_RES_NAME, R_TABLE FROM DEC20_RESTAURANT WHERE R_LOCATION = '강남';

-- 최연장자 사장님 이름, 집
SELECT C_NAME, C_HOME FROM DEC20_CEO WHERE C_BIRT = (SELECT MIN(C_BIRT) FROM DEC20_CEO);

-- 가게의 총 개수
SELECT COUNT(*) FROM DEC20_RESTAURANT;

-- '밥' 시리즈의 평균가
SELECT AVG(M_PRICE) FROM DEC20_MENU WHERE M_NAME LIKE '%밥%';

----------------------------------------------------------------------------------------------------

-- 강남에 가면 뭘 먹을 수 있나
-- 위치가 강남인 식당의 번호
SELECT C_NO FROM DEC20_RESTAURANT WHERE R_LOCATION = '강남';)
SELECT M_NAME FROM DEC20_MENU WHERE M_RE_NO = (SELECT C_NO FROM DEC20_RESTAURANT WHERE R_LOCATION = '강남');


-- 제일 비싼 메뉴 어디가면 먹을 수 있나
-- 제일 비싼 메뉴
SELECT MAX(M_PRICE) FROM DEC20_MENU;
-- 제일 비싼 메뉴 식당 번호
SELECT M_RE_NO FROM DEC20_MENU WHERE M_PRICE = (SELECT MAX(M_PRICE) FROM DEC20_MENU);
-- 식당번호에 해당하는 식당의 위치
SELECT R_LOCATION FROM DEC20_RESTAURANT WHERE C_NO = (SELECT M_RE_NO FROM DEC20_MENU WHERE M_PRICE = (SELECT MAX(M_PRICE) FROM DEC20_MENU));


-- 홍길동 가게 메뉴명, 가격
-- 메뉴명과 가격
SELECT M_NAME, M_PRICE FROM DEC20_MENU;
-- 홍길동 가게 번호
SELECT C_NO FROM DEC20_CEO WHERE C_NAME = '홍길동';

SELECT M_NAME, M_PRICE FROM DEC20_MENU WHERE M_RE_NO = (SELECT C_NO FROM DEC20_CEO WHERE C_NAME = '홍길동');


-- 최연장자 사장님네 메뉴 평균가
-- 메뉴 평균가
SELECT AVG(M_PRICE) FROM DEC20_MENU;
-- 최연장자
SELECT MIN(C_BIRT) FROM DEC20_CEO;
-- 최연장자의 가게 번호
SELECT C_NO FROM DEC20_CEO WHERE C_BIRT = (SELECT MIN(C_BIRT) FROM DEC20_CEO);


