CREATE TABLE DEC23_STORE (
	S_NO NUMBER(3) PRIMARY KEY,
	S_BRAND VARCHAR2(10 CHAR) NOT NULL,
	S_LOCATION VARCHAR2(20 CHAR) NOT NULL,
	S_ADDR VARCHAR2(20 CHAR) NOT NULL
);

CREATE SEQUENCE DEC23_STORE_SEQ;
INSERT INTO DEC23_STORE VALUES (DEC23_STORE_SEQ.NEXTVAL, '미니스톱', '금천가산점', '가산로134');
INSERT INTO DEC23_STORE VALUES (DEC23_STORE_SEQ.NEXTVAL, '미니스톱', '가산노블루체점', '가산로9길17');
INSERT INTO DEC23_STORE VALUES (DEC23_STORE_SEQ.NEXTVAL, '이마트24', '가산지웰점', '가산로9길 12-8');
INSERT INTO DEC23_STORE VALUES (DEC23_STORE_SEQ.NEXTVAL, '세븐일레븐', '금천가산점', '가산로 147-7');
INSERT INTO DEC23_STORE VALUES (DEC23_STORE_SEQ.NEXTVAL, '세븐일레븐', '가리봉2호점', '가리봉동135-70');
INSERT INTO DEC23_STORE VALUES (DEC23_STORE_SEQ.NEXTVAL, 'CU', '가산조이점', '가산로7길12');
INSERT INTO DEC23_STORE VALUES (DEC23_STORE_SEQ.NEXTVAL, 'CU', '가산디지털점', '가산로 157');
INSERT INTO DEC23_STORE VALUES (DEC23_STORE_SEQ.NEXTVAL, 'GS25', '금천하이힐점', '디지털로12길 21');
INSERT INTO DEC23_STORE VALUES (DEC23_STORE_SEQ.NEXTVAL, 'GS25', '가산태양점', '가산동149-27');


CREATE TABLE DEC23_PRODUCT (
P_NAME VARCHAR(50 CHAR) PRIMARY KEY,
P_CATEGORY VARCHAR(10 CHAR) NOT NULL,
P_PRICE NUMBER(5) NOT NULL,
P_EVENT_NO NUMBER(2) NOT NULL,
CONSTRAINT EVENT_DELETE foreign KEY (P_EVENT_NO) REFERENCES DEC23_EVENT(E_NO) ON DELETE CASCADE
);

INSERT INTO DEC23_PRODUCT VALUES ('유어스(P)슈퍼말차워터500ML', '음료', 2000, 2);
INSERT INTO DEC23_PRODUCT VALUES ('유어스(P)톰과제리초코캔200ML', '음료', 2000, 2);
INSERT INTO DEC23_PRODUCT VALUES ('돌)파인애플컵198G', '과일', 2900, 1);
INSERT INTO DEC23_PRODUCT VALUES ('CLOOP)제로소다복숭아500ML', '음료', 2200, 1);
INSERT INTO DEC23_PRODUCT VALUES ('소포장)청결미1KG(봉)', '쌀', 6500, 1);
INSERT INTO DEC23_PRODUCT VALUES ('CJ)가쓰오우동(용기)', '컵라면', 3900, 3);
INSERT INTO DEC23_PRODUCT VALUES ('편스)어남선생햄듬뿍로제부대', '컵라면', 4300, 3);




DROP table DEC23_STORE CASCADE CONSTRAINT PURGE;
DROP table DEC23_PRODUCT CASCADE CONSTRAINT PURGE;

CREATE TABLE DEC23_EVENT (
E_NO NUMBER(2) PRIMARY KEY,
E_NAME VARCHAR2(10 CHAR) NOT NULL,
E_START DATE NOT NULL,
E_END DATE NOT NULL
);


CREATE SEQUENCE DEC23_EVENT_SEQ;
INSERT INTO DEC23_EVENT VALUES (DEC23_EVENT_SEQ.NEXTVAL, '1+1', TO_DATE('20221201', 'YYYYMMDD'), TO_DATE('20221231', 'YYYYMMDD'));
INSERT INTO DEC23_EVENT VALUES (DEC23_EVENT_SEQ.NEXTVAL, '2+1', TO_DATE('20221201', 'YYYYMMDD'), TO_DATE('20221231', 'YYYYMMDD'));
INSERT INTO DEC23_EVENT VALUES (DEC23_EVENT_SEQ.NEXTVAL, '덤증정', TO_DATE('20221201', 'YYYYMMDD'), TO_DATE('20221231', 'YYYYMMDD'));

SELECT * FROM DEC23_STORE;
SELECT * FROM DEC23_PRODUCT;
SELECT * FROM DEC23_EVENT;

SELECT count(*) FROM DEC23_PRODUCT;
